name: tfkeras
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - black=24.10.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - click=8.1.8
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.7.1
  - flake8=7.1.1
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - icu=73.1
  - iniconfig=1.1.1
  - ipython=9.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jpeg=9e
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libcups=2.4.2
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.7
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mypy_extensions=1.0.0
  - mysql=8.4.0
  - ncurses=6.4
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.16
  - parso=0.8.4
  - pathspec=0.10.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycodestyle=2.12.1
  - pyflakes=3.2.0
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pytest=8.3.4
  - python=3.12.9
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - readline=8.2
  - setuptools=75.8.0
  - sip=6.10.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tk=8.6.14
  - traitlets=5.14.3
  - unicodedata2=15.1.0
  - wcwidth=0.2.5
  - wheel=0.45.1
  - xcb-util-cursor=0.1.4
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.2.2
      - anyio==4.9.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array-record==0.7.1
      - arrow==1.3.0
      - astunparse==1.6.3
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - behave==1.2.6
      - bleach==6.2.0
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - comm==0.2.2
      - debugpy==1.8.14
      - defusedxml==0.7.1
      - dm-tree==0.1.9
      - docstring-parser==0.16
      - einops==0.8.1
      - etils==1.12.2
      - fastjsonschema==2.21.1
      - flatbuffers==25.2.10
      - fqdn==1.5.1
      - fsspec==2025.3.2
      - gast==0.6.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.70.0
      - grpcio==1.71.0
      - h11==0.16.0
      - h5py==3.13.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - immutabledict==4.2.1
      - importlib-resources==6.5.2
      - ipykernel==6.29.5
      - ipywidgets==8.1.6
      - isoduration==20.11.0
      - jinja2==3.1.6
      - joblib==1.4.2
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.14
      - kaggle==1.7.4.2
      - kagglehub==0.3.12
      - keras==3.9.2
      - keras-core==0.1.7
      - keras-cv==0.9.0
      - keras-hub==0.20.0
      - keras-tuner==1.4.7
      - kt-legacy==1.0.5
      - libclang==18.1.1
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mistune==3.1.3
      - ml-dtypes==0.5.1
      - namex==0.0.9
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.4.1
      - notebook-shim==0.2.4
      - numpy==2.1.3
      - opt-einsum==3.4.0
      - optree==0.15.0
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parse==1.20.2
      - parse-type==0.6.4
      - prometheus-client==0.21.1
      - promise==2.3
      - protobuf==5.29.4
      - psutil==7.0.0
      - pyarrow==19.0.1
      - pycparser==2.22
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - python-slugify==8.0.4
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rpds-py==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - send2trash==1.8.3
      - simple-parsing==0.1.7
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.7
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-datasets==4.9.8
      - tensorflow-metadata==1.17.1
      - tensorflow-text==2.19.0
      - termcolor==3.0.1
      - terminado==0.18.1
      - text-unidecode==1.3
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - toml==0.10.2
      - tornado==6.4.2
      - tqdm==4.67.1
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.4.0
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - zipp==3.21.0
